language: ruby
cache: bundler

rvm:
  - 2.2.3
script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - makinwa37@gmail.com
    on_failure: change
    on_success: never

before_install: gem install bundler -v 1.11.1
